version: '3.8'

services:
  mongo:
    image: mongo:4.4.6
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongo_data:/data/db