GET http://localhost:3000/todos
#####

POST http://localhost:3000/todos
Content-Type: application/json

{"text": "for exercise 12.12 (3, last) "}

#####

GET http://localhost:3000/todos/63e160a144a52e3b700164e5


######

DELETE http://localhost:3000/todos/63e413a76110e456ab9e697f

######

PUT http://localhost:3000/todos/63e160a144a52e3b700164e5

####

GET http://localhost:3000/statistics